# fly.toml file generated for chatterbox-go on 2023-12-30T16:14:24+03:00

app = "chatterbox-go"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "fra"
processes = []

[build]
  dockerfile = "./Dockerfile"

[env]
  APP_PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
